export const SCALE_TYPES = {
	Major: 'Major',
	Minor: 'Minor',
	Chromatic: 'Chromatic',
	Pentatonic: 'Pentatonic',
	'Whole Tone': 'Whole Tone',
	Blues: 'Blues',
	Dorian: 'Dorian',
	Mixolydian: 'Mixolydian',
	Lydian: 'Lydian',
	Phrygian: 'Phrygian',
	Locrian: 'Locrian',
	'Harmonic Minor': 'Harmonic Minor',
	'Melodic Minor': 'Melodic Minor',
	Augmented: 'Augmented',
	Diminished: 'Diminished',
	Arabic: 'Arabic',
	Hungarian: 'Hungarian',
	Neapolitan: 'Neapolitan',
	'Lydian Dominant': 'Lydian Dominant',
	'Double Harmonic': 'Double Harmonic',
	Bebop: 'Bebop',
	'Jazz Minor': 'Jazz Minor',
	Altered: 'Altered',
}

export const ROOT_NOTES = {
	C: 'C',
	'C#': 'C#',
	D: 'D',
	'D#': 'D#',
	E: 'E',
	F: 'F',
	'F#': 'F#',
	G: 'G',
	'G#': 'G#',
	A: 'A',
	'A#': 'A#',
	B: 'B',
}
